---
title: "7 – Lösungen"
subtitle: "Statistische Datenanalyse mit R"
author: "Clemens Brunner"
date: 2026-11-12
format:
  html:
    page-layout: full
engine: knitr
knitr:
  opts_chunk: 
    R.options:
      width: 120
highlight-style: github
title-block-banner: true
theme:
  light: flatly
  dark: darkly
lang: de
author-title: "Autor"
published-title: "Veröffentlicht"
---

## Übung 1

```{r}
#| message: false
library(dplyr)

mtcars1 = mtcars |>
    filter(mpg > 25)

nrow(mtcars)  # 32 Zeilen
nrow(mtcars1)  # 6 Zeilen
ncol(mtcars)  # 11 Spalten (unverändert)
```


## Übung 2

```{r}
library(nycflights13)

flights |>
    filter(day == 1, month == 1) |>  # 842 Zeilen
    select(year:dep_time, arr_time, tailnum)

flights |>
    mutate(
        hours=air_time / 60,
        km=distance * 1.60934,
        speed=km / hours
    ) |>
    select(month, day, carrier, tailnum, speed)

flights |>
    filter(dep_time < 600)  # 8730 Zeilen

flights |>
    filter(arr_delay < dep_delay)  # 221565 Zeilen
```


## Übung 3

```{r}
penguins |>
    group_by(species) |>
    summarize(
        n=n(),
        bill_len=mean(bill_len, na.rm=TRUE),
        bill_dep=mean(bill_dep, na.rm=TRUE),
        flipper_len=mean(flipper_len, na.rm=TRUE)
    )
```

Ohne `na.rm=TRUE` wären die Mittelwerte für Adélie und Gentoo `NA`, weil es in diesen Spalten jeweils zwei fehlende Werte gibt.


## Übung 4

```{r}
#| message: false
library(readr)

df = read_tsv("lecturer.dat")

df |>
    group_by(job) |>
    summarize(
        n=n(),
        friends=mean(friends),
        alcohol=mean(alcohol),
        income=mean(income),
        neurotic=mean(neurotic)
    ) |>
    arrange(desc(income))
```

Die Spalte `job` liegt hier als Zahl (1 bzw. 2) vor, weil wir sie nicht wie in Einheit 6 in einen Faktor konvertiert haben. Für die Gruppierung selbst macht das keinen Unterschied.
