---
title: "11 – Lösungen"
subtitle: "Statistische Datenanalyse mit R"
author: "Clemens Brunner"
date: 2023-01-19
format: html
engine: knitr
highlight-style: github
title-block-banner: true
theme:
  light: flatly
  dark: darkly
lang: de
author-title: "Autor"
published-title: "Veröffentlicht"
---

## Übung 1

```{r}
#| message: false
library(readr)
library(tibble)

sales = read_tsv("sales2.dat")
sales = as_tibble(scale(sales))
model = lm(sales ~ adverts + airplay + attract, data=sales)
summary(model)
coef(model)  # stimmt mit lm.beta überein
```


## Übung 2

```{r}
#| message: false
library(lm.beta)  # für lm.beta

aggression = read_tsv("aggression.dat")

model1 = lm(Aggression ~ Parenting_Style + Sibling_Aggression, data=aggression)
summary(model1)  # beide Variablen erwartungsgemäß signifikant
lm.beta(model1)  # Parenting_Style hat größeren Einfluss als Sibling_Aggression

model2 = lm(
    Aggression ~ Parenting_Style + Sibling_Aggression + Television +
                 Computer_Games + Diet,
    data=aggression
)
summary(model2)
lm.beta(model2)

anova(model1, model2)  # Vergleich beider Modelle
```


## Übung 3

```{r}
library(car)  # für dwt, vif

# Kollinearität
vif(model2)

# Unabhängigkeit der Residuen
dwt(model2)

# Normalverteilung Residuen
plot(model2, which=2)

# Linearität und Varianzhomogenität
plot(model2, which=1)

# Punkte mit großem Einfluss
plot(model2, which=5)
```


## Übung 4

```r
influence.measures(model2)
```

```r
# oder mit einzelnen Funktionen
dfbeta(model2)
cooks.distance(model2)
resid(model2)
rstandard(model2)
rstudent(model2)
dffits(model2)
hatvalues(model2)
```

```{r}
# Anzahl rstandard > 3
sum(rstandard(model2) > 3)

# Anzahl rstandard < -3
sum(rstandard(model2) < -3)

# Relativer Anteil an |rstandard| > 2
sum(abs(rstandard(model2)) > 2) / nrow(aggression)
```
