---
title: "Review"
subtitle: "Statistical Data Analysis with R"
author: "Clemens Brunner"
date: 2024-11-14
format:
  html:
    page-layout: full
engine: knitr
knitr:
  opts_chunk: 
    R.options:
      width: 120
highlight-style: github
title-block-banner: true
theme:
  light: flatly
  dark: darkly
---

## Exercise 1

Consider the `penguins` data frame from the `palmerpenguins` package. Determine whether the three species (Adélie, Chinstrap, Gentoo) differ in terms of body mass (column `body_mass_g`). Perform the following steps:

a. Check if there are missing values in the `body_mass_g` column. If so, remove the corresponding rows from the data frame.
b. Calculate the means and standard deviations of body mass for each species.
c. Add a column named `id` to the data frame, which contains the row number (1 for the first row, 2 for the second row, etc.). This column uniquely identifies each observation (each penguin). The `nrow()` function might be helpful.
d. Install and activate the `afex` package. Perform a one-way ANOVA to test whether the species differ significantly in terms of body mass using the `aov_ez()` function.


## Exercise 2

The `rnorm()` function generates normally distributed random numbers. Generate 1000 random numbers from a normal distribution with a mean of 10 and a standard deviation of 2 and store them in a data frame `df` column named `x`. Add another column `y` containing random values from the `LETTERS` vector; use the `sample()` function with the argument `replace=TRUE`. Finally, add a third column named `z` containing the squares of the values in the `x` column.

:::{.callout-tip}
Before generating the random numbers, set the random number generator to a defined state using `set.seed(123)` to obtain reproducible results.
:::

a. What are the means of the `x` and `z` columns?
b. How many values in the `y` column are equal to `"A"`?
c. How many values in the `z` column are greater than 100?
d. How many values in the `y` column are equal to `"A"` and have corresponding values in the `z` column greater than 100?


## Exercise 3

Given the `penguins` data frame from the `palmerpenguins` package, how many female and male penguins does the data set contain? How many missing values does the `sex` column contain? Create two new data frames `penguins_f` and `penguins_m` containing only the female and male penguins, respectively.


## Exercise 4

Create a vector `x` containing the odd numbers from 1 to 100. Calculate the mean, standard deviation, median, 25th percentile, and 75th percentile of `x`.


## Exercise 5

a. Create a matrix `m1` with 25 rows and 5 columns. Fill each column with the numbers 1 to 5, so that column 1 contains only 1s, column 2 contains only 2s, and so on. Calculate the row and column sums!
b. Create a second matrix `m2` with the same dimensions, but fill each row with the numbers from 1 to 25, so that row 1 contains only 1s, row 2 contains only 2s, and so on. Calculate the row and column sums!


## Exercise 6

Official data on Austrian greenhouse gas emissions are available [here](https://www.data.gv.at/katalog/dataset/78bd7b69-c1a7-456b-8698-fac3b24f7aa5#resources). Download this data set (in long format) or use the file [`thg-emissionen_1990-2022_nach_crf_long.csv`](thg-emissionen_1990-2022_nach_crf_long.csv).

Import this dataset into R and answer the following questions:

a. How many different pollutants are recorded in this dataset (column `Schadstoff`)?
b. How many different CRF codes are available (CRF is short for [Common Reporting Format](https://en.eustat.eus/documentos/elem_13127/definicion.html) and defines the allocation of emissions to sectors)?
c. Create a new data frame `df` containing only the CO₂ emissions (column `Schadstoff`) across all sectors (corresponding to a CRF code of 0).
