---
title: "Übungen"
subtitle: "Statistische Datenanalyse mit R"
author: "Clemens Brunner"
date: 2024-11-14
format:
  html:
    page-layout: full
engine: knitr
knitr:
  opts_chunk: 
    R.options:
      width: 120
highlight-style: github
title-block-banner: true
theme:
  light: flatly
  dark: darkly
lang: de
author-title: "Autor"
published-title: "Veröffentlicht"
---

## Übung 1

Wir betrachten das Data Frame `penguins` aus dem Paket `palmerpenguins`. Untersuchen Sie, ob sich die drei Spezies (Adélie, Chinstrap, Gentoo) in Bezug auf die Körpermasse (Spalte `body_mass_g`) unterscheiden.

a. Überprüfen Sie, ob es fehlende Werte in der Spalte `body_mass_g` gibt. Falls ja, entfernen Sie die entsprechenden Zeilen aus dem Data Frame.
b. Berechnen Sie die Mittelwerte und Standardabweichungen der Körpermasse für jede Spezies.
c. Fügen Sie dem Data Frame eine Spalte namens `id` hinzu, welche die Zeilennummer enthält (1 für die erste Zeile, 2 für die zweite Zeile, usw.). Diese Spalte identifiziert also jede Beobachtung (jeden Pinguin) eindeutig. Die Funktion `nrow()` könnte dabei hilfreich sein.
d. Installieren und aktivieren Sie das Paket `afex`. Führen Sie eine einfaktorielle ANOVA durch, um zu überprüfen, ob sich die Körpermasse zwischen den Spezies unterscheidet. Verwenden Sie die Funktion `aov_ez()`. Unterscheiden sich die Spezies signifikant in Bezug auf die Körpermasse?


## Übung 2

Die Funktion `rnorm()` erzeugt normalverteilte Zufallszahlen. Erzeugen Sie 1000 Zufallszahlen aus einer Normalverteilung mit einem Mittelwert von 10 und einer Standardabweichung von 2 und speichern Sie diese in in einem Data Frame `df` mit einer Spalte namens `x`. Fügen Sie eine weitere Spalte `y` hinzu, welche zufällige Werte aus dem Vektor `LETTERS` enthält; verwenden Sie dazu die Funktion `sample()` mit dem Argument `replace=TRUE`. Fügen Sie schließlich eine dritte Spalte namens `z` hinzu, welche die Quadrate der Werte in der Spalte `x` enthält.

:::{.callout-tip}
Bevor Sie die Zufallszahlen erzeugen, setzen Sie den Zufallszahlengenerator mit `set.seed(123)` in einen definierten Ausgangszustand, um reproduzierbare Ergebnisse zu erhalten.
:::

a. Wie lauten die Mittelwerte der Spalten `x` und `z`?
b. Wie viele Werte in der Spalte `y` sind gleich `"A"`?
c. Wie viele Werte in der Spalte `z` sind größer als 100?
d. Wie viele Werte in der Spalte `y` sind gleich `"A"` und deren zugehörige Werte in der Spalte `z` größer als 100?


## Übung 3

Gegeben sei das Data Frame `penguins` aus dem Paket `palmerpenguins`. Wie viele weibliche und männliche Pinguine gibt es im Datensatz? Wie viele fehlende Werte gibt es in der Spalte `sex`? Erzeugen Sie zwei neue Data Frames `penguins_f` und `penguins_m`, welche nur die weiblichen bzw. männlichen Pinguine enthalten!


## Übung 4

Erzeugen Sie einen Vektor `x` mit den ungeraden Zahlen von 1 bis 100. Berechnen Sie den Mittelwert, die Standardabweichung, den Median, das 25. Perzentil und das 75. Perzentil von `x`.


## Übung 5

a. Erstellen Sie eine Matrix `m1`, welche aus 25 Zeilen und 5 Spalten besteht. Die fünf Spalten sollen jeweils mit den Zahlen 1 bis 5 gefüllt werden. Berechnen Sie die Zeilen- und Spaltensummen!
b. Erstellen eine zweite Matrix `m2` mit denselben Dimensionen, wobei nun die 25 Zeilen jeweils mit den Zahlen von 1 bis 25 gefüllt werden sollen. Berechnen Sie die Zeilen- und Spaltensummen!


## Übung 6

Die offiziellen Daten zu den österreichischen Treibhausgasemissionen sind [hier](https://www.data.gv.at/katalog/dataset/78bd7b69-c1a7-456b-8698-fac3b24f7aa5#resources) verfügbar. Laden Sie diesen Datensatz (im Long-Format) herunter bzw. verwenden Sie die Datei [`thg-emissionen_1990-2022_nach_crf_long.csv`](thg-emissionen_1990-2022_nach_crf_long.csv).

Importieren Sie diesen Datensatz in R und beantworten Sie folgende Fragen:

a. Wie viele verschiedene Schadstoffe werden in diesem Datensatz erfasst?
b. Wie viele verschiedene CRF-Codes gibt es (CRF bedeutet [Common Reporting Format](https://en.eustat.eus/documentos/elem_13127/definicion.html) und definiert u.a. die Aufteilung der Emissionen in verursachende Sektoren)?
c. Erstellen Sie ein neues Data Frame `df`, welches nur die CO₂-Emissionen über alle Sektoren (entspricht einem CRF-Code von 0) enthält.
