---
title: "Organisatorisches"
subtitle: "Statistische Datenanalyse mit R"
author: "Clemens Brunner"
date: 2026-10-01
format:
  html:
    page-layout: full
engine: knitr
knitr:
  opts_chunk: 
    R.options:
      width: 120
highlight-style: github
title-block-banner: true
theme:
  light: flatly
  dark: darkly
lang: de
author-title: "Autor"
published-title: "Veröffentlicht"
---

## Allgemeines

In dieser Lehrveranstaltung lernen Sie das Statistikpaket [R](https://www.r-project.org/) kennen. Die Lehrveranstaltung vermittelt die Grundlagen von R und setzt keinerlei Vorkenntnisse voraus. Aufgrund der begrenzten Zeit können wir daher nicht alle in der Praxis relevanten statistischen Verfahren behandeln. Das erworbene Basiswissen ermöglicht es Ihnen jedoch, sich später weitere statistische Methoden selbstständig anzueignen.

Der Plan für dieses Semester sieht wie folgt aus:

| Einheit | Datum      | Inhalt                  |
|--------:|-----------:|-------------------------|
| 1       |  1.10.2026 | Erste Schritte          |
| 2       |  8.10.2026 | Die R-Umgebung          |
| 3       | 15.10.2026 | Vektoren                |
| 4       | 22.10.2026 | Tabellen                |
| 5       | 29.10.2026 | Daten importieren       |
| 6       |  5.11.2026 | Deskriptive Statistiken |
| 7       | 12.11.2026 | Datenaufbereitung       |
| 8       | 19.11.2026 | Grafiken                |
| 9       | 26.11.2026 | Korrelation             |
| 10      |  3.12.2026 | Lineare Regression (1)  |
| 11      | 10.12.2026 | Lineare Regression (2)  |
| 12      | 17.12.2026 | Mittelwertvergleich     |
| 13      |  14.1.2027 | Übungen                 |
| 14      |  21.1.2027 | Prüfung                 |
| 15      |  28.1.2027 | Prüfung (Ersatztermin)  |

: {tbl-colwidths="[10,10,80]"}

Alle Informationen und Unterlagen zu dieser Lehrveranstaltung werden auf [Moodle](https://moodle.uni-graz.at/login/index.php) zur Verfügung gestellt. Insbesondere wird auch die Kommunikation (Ankündigungen, Forumsdiskussionen, Fragen & Antworten) über Moodle abgewickelt.

Die Einheiten finden grundsätzlich in Präsenz statt. Sollte das einmal nicht möglich sein, wird dies auf Moodle bekanntgegeben und die betreffende Einheit wird gegebenenfalls zur geplanten Zeit online abgehalten.


## Ablauf einer Einheit

Zu jeder Einheit gibt es auf Moodle ausführliche Unterlagen, welche das jeweilige Thema detailliert behandeln. Diese Unterlagen sind so gestaltet, dass Sie sich die Inhalte im Selbststudium aneignen können. Alle inhaltlichen Einheiten (mit Ausnahme der ersten) werden nach dem Prinzip des [Flipped Classroom](https://de.wikipedia.org/wiki/Umgedrehter_Unterricht) abgehalten. Das bedeutet, dass Sie die Inhalte der jeweiligen Einheit *vor* dem tatsächlichen Termin erarbeiten müssen. Besonders wichtig sind die Übungsbeispiele am Ende jedes Kapitels. Diese überprüfen Ihr Verständnis der vermittelten Inhalte und sind außerdem eine essenzielle Vorbereitung für die abschließende Prüfung am Ende des Semesters.

::: callout-tip
Nutzen Sie während der Vorbereitungszeit das Diskussionsforum auf Moodle – dort können Sie Fragen stellen und selbstverständlich auch beantworten. Je mehr Personen sich aktiv im Forum beteiligen, desto hilfreicher wird es für alle!
:::

::: callout-tip
Wenn Sie die Möglichkeit haben, sich die Inhalte gemeinsam mit anderen Studierenden zu erarbeiten, ist das natürlich umso besser! Gerade bei Programmieraufgaben ist es oft hilfreich, sich auszutauschen und gemeinsam Lösungen zu erarbeiten ([Pair Programming](https://de.wikipedia.org/wiki/Paarprogrammierung)).
:::

Jede Einheit beginnt mit einem kurzen Quiz zum Thema der jeweiligen Einheit (dazu später mehr). Danach werden die von Ihnen vorbereiteten Übungsbeispiele aus den Unterlagen detailliert besprochen und Musterlösungen präsentiert. Dabei haben Sie die Möglichkeit, Fragen zu stellen bzw. Ihre individuellen Lösungsansätze zu diskutieren. Falls darüber hinaus noch Zeit bleiben sollte, wird das jeweilige Thema durch vertiefende Beispiele bzw. Erklärungen ergänzt.

::: callout-note
Der Einsatz von Künstlicher Intelligenz (KI), insbesondere von Large Language Models (LLMs, wie z.B. [Claude](https://claude.ai/), [ChatGPT](https://chatgpt.com/), [Gemini](https://gemini.google.com/app), oder [Mistral](https://mistral.ai/)), ist für die Vorbereitung der Einheiten ausdrücklich erlaubt und wird sogar empfohlen. Diese Werkzeuge können helfen, Konzepte zu verstehen, Codebeispiele nachzuvollziehen und alternative Erklärungen zu finden. Allerdings sollten Sie immer versuchen, die Übungsaufgaben selbständig zu lösen, um ein Verständnis der Materie zu entwickeln. Lassen Sie sich also von den KI-Tools Dinge erklären, aber kopieren Sie nicht einfach fertige Lösungen!
:::


## Beurteilungskriterien

### Anwesenheit

Durch den immanenten Prüfungscharakter dieser Lehrveranstaltung besteht Anwesenheitspflicht. Ihre Anwesenheit wird zu einem zufälligen Zeitpunkt während der Einheit überprüft. Sie können allerdings ohne Auswirkungen auf die Beurteilung bei bis zu drei Einheiten fehlen (eine Begründung ist nicht erforderlich).


### Quizzes

Zu Beginn jeder Einheit (mit Ausnahme der ersten) findet ein Quiz auf Moodle statt. Es werden kurze Fragen zum jeweiligen Thema der Einheit gestellt (meist Multiple-Choice). Hilfsmittel (wie z.B. die Unterlagen) sind *nicht* erlaubt!

Sie können bei einem Quiz maximal 10 Punkte erreichen (es gibt auch Teilpunkte). Das Quiz muss *vor Ort* auf einem Universitäts-PC absolviert werden. Ein nicht absolviertes Quiz (z.B. durch Fehlen oder Zuspätkommen) zählt 0 Punkte.

::: callout-note
Stellen Sie vorab sicher, dass Ihre aktuellen Zugangsdaten (einschließlich der Zwei-Faktor-Authentifizierung) für die Anmeldung funktionieren!
:::


### Prüfung

Am Ende des Semesters findet eine Prüfung über alle Inhalte der Lehrveranstaltung statt, welche vor Ort auf einem Universitäts-PC absolviert wird. Als einziges Hilfsmittel ist ein von Ihnen erstelltes, zweiseitig beschriebenes A4-Blatt erlaubt, auf dem Sie die wichtigsten Inhalte der Lehrveranstaltung zusammenfassen können (Cheat Sheet). Fertig gelöste Beispiele dürfen darauf jedoch nicht enthalten sein. Der Cheat Sheet ist direkt nach der Prüfung abzugeben. Wenn dieser selbständig gestaltet und gut strukturiert ist, werden 0.25 Zusatzpunkte auf die Prüfungspunkte angerechnet.

Da Sie mit RStudio arbeiten werden (Ihre Lösung ist dann als R-Script auf Moodle abzugeben), können Sie natürlich auch die integrierte Hilfe von R nutzen, um Informationen zu Funktionen oder Paketen abzurufen.

Es können maximal 10 Punkte erreicht werden (Teilpunkte sind möglich). Bei der Prüfung gibt es eine Bonusaufgabe, die 1 Zusatzpunkt einbringt. Die maximal erreichbare Punktezahl bei der Prüfung beträgt aber in jedem Fall 10 Punkte.

Die Prüfung kann bei Bedarf wiederholt werden. In diesem Fall zählen die Punkte des zweiten Termins, d.h. man kann sich sowohl verbessern als auch verschlechtern.


## Benotung

Die Gesamtnote ergibt sich aus den drei beschriebenen Kriterien:

- Wenn Sie nicht öfter als drei Mal gefehlt haben, ist das Anwesenheitskriterium erfüllt. Mehr als drei Fehleinheiten führen automatisch zu einer negativen Beurteilung der Lehrveranstaltung.
- Aus den Punkten aller Quizzes werden zunächst die *niedrigsten drei* Bewertungen entfernt. Aus den übrigen Bewertungen wird der arithmetische Mittelwert berechnet – dieser Mittelwert fließt dann zu 50% in die Gesamtnote ein.
- Die Punkte aus der Prüfung fließen ebenfalls zu 50% in die Gesamtnote ein. Es müssen allerdings *mindestens* 6 Punkte bei der Prüfung erreicht werden, um die Lehrveranstaltung positiv abzuschließen.

Sofern diese Kriterien erfüllt sind, ergibt sich die Gesamtnote aus dem Mittelwert der Punkte aus den Quizzes und der Prüfung wie folgt:

| Sehr gut    | Gut        | Befriedigend | Genügend   | Nicht genügend |
|-------------|------------|--------------|------------|----------------|
| 9–10 Punkte | 8–9 Punkte | 7–8 Punkte   | 6–7 Punkte | \< 6 Punkte    |

Die niedrigste Punkteanzahl einer Kategorie wird immer der besseren Note zugeordnet (beispielsweise entsprechen exakt 9 Punkte der Note "Sehr gut"). Die gemittelte Punkteanzahl wird nicht mehr auf- oder abgerundet, daher entsprechen z.B. 8.99 Punkte der Note "Gut".
